# coding: utf-8

"""
    Sipher — Privacy-as-a-Skill API

    REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

    The version of the OpenAPI document: 0.1.0
    Contact: hello@sip-protocol.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sipher_client.models.decrypt_inco_result200_response import DecryptIncoResult200Response

class TestDecryptIncoResult200Response(unittest.TestCase):
    """DecryptIncoResult200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DecryptIncoResult200Response:
        """Test DecryptIncoResult200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DecryptIncoResult200Response`
        """
        model = DecryptIncoResult200Response()
        if include_optional:
            return DecryptIncoResult200Response(
                success = True,
                beta = True,
                data = sipher_client.models.decrypt_inco_result_200_response_data.decryptIncoResult_200_response_data(
                    computation_id = '', 
                    operation = '', 
                    decrypted_output = '', 
                    verification_hash = '', )
            )
        else:
            return DecryptIncoResult200Response(
        )
        """

    def testDecryptIncoResult200Response(self):
        """Test DecryptIncoResult200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
