# coding: utf-8

"""
    Sipher — Privacy-as-a-Skill API

    REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

    The version of the OpenAPI document: 0.1.0
    Contact: hello@sip-protocol.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sipher_client.models.stealth_check200_response import StealthCheck200Response

class TestStealthCheck200Response(unittest.TestCase):
    """StealthCheck200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StealthCheck200Response:
        """Test StealthCheck200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StealthCheck200Response`
        """
        model = StealthCheck200Response()
        if include_optional:
            return StealthCheck200Response(
                success = True,
                data = sipher_client.models.stealth_check_200_response_data.stealthCheck_200_response_data(
                    is_owner = True, )
            )
        else:
            return StealthCheck200Response(
        )
        """

    def testStealthCheck200Response(self):
        """Test StealthCheck200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
