# coding: utf-8

"""
    Sipher — Privacy-as-a-Skill API

    REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

    The version of the OpenAPI document: 0.1.0
    Contact: hello@sip-protocol.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sipher_client.models.backends_compare_request import BackendsCompareRequest

class TestBackendsCompareRequest(unittest.TestCase):
    """BackendsCompareRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BackendsCompareRequest:
        """Test BackendsCompareRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BackendsCompareRequest`
        """
        model = BackendsCompareRequest()
        if include_optional:
            return BackendsCompareRequest(
                operation = 'stealth_privacy',
                chain = 'solana',
                amount = '68072888001528021798096225500',
                prioritize = 'cost'
            )
        else:
            return BackendsCompareRequest(
                operation = 'stealth_privacy',
        )
        """

    def testBackendsCompareRequest(self):
        """Test BackendsCompareRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
