# coding: utf-8

"""
    Sipher — Privacy-as-a-Skill API

    REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

    The version of the OpenAPI document: 0.1.0
    Contact: hello@sip-protocol.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sipher_client.models.backends_list200_response_data_backends_inner_capabilities import BackendsList200ResponseDataBackendsInnerCapabilities

class TestBackendsList200ResponseDataBackendsInnerCapabilities(unittest.TestCase):
    """BackendsList200ResponseDataBackendsInnerCapabilities unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BackendsList200ResponseDataBackendsInnerCapabilities:
        """Test BackendsList200ResponseDataBackendsInnerCapabilities
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BackendsList200ResponseDataBackendsInnerCapabilities`
        """
        model = BackendsList200ResponseDataBackendsInnerCapabilities()
        if include_optional:
            return BackendsList200ResponseDataBackendsInnerCapabilities(
                hidden_amount = True,
                hidden_sender = True,
                hidden_recipient = True,
                hidden_compute = True,
                compliance_support = True,
                setup_required = True,
                latency_estimate = 'fast',
                supported_tokens = 'native',
                min_amount = '',
                max_amount = ''
            )
        else:
            return BackendsList200ResponseDataBackendsInnerCapabilities(
        )
        """

    def testBackendsList200ResponseDataBackendsInnerCapabilities(self):
        """Test BackendsList200ResponseDataBackendsInnerCapabilities"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
