# coding: utf-8

"""
    Sipher — Privacy-as-a-Skill API

    REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

    The version of the OpenAPI document: 0.1.0
    Contact: hello@sip-protocol.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sipher_client.models.compute_inco_ciphertexts200_response import ComputeIncoCiphertexts200Response

class TestComputeIncoCiphertexts200Response(unittest.TestCase):
    """ComputeIncoCiphertexts200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ComputeIncoCiphertexts200Response:
        """Test ComputeIncoCiphertexts200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ComputeIncoCiphertexts200Response`
        """
        model = ComputeIncoCiphertexts200Response()
        if include_optional:
            return ComputeIncoCiphertexts200Response(
                success = True,
                beta = True,
                warning = '',
                data = sipher_client.models.compute_inco_ciphertexts_200_response_data.computeIncoCiphertexts_200_response_data(
                    computation_id = 'inc_62ECB020842930cc01FFCCfeEe150AC32DcAEc8a83DDD7dBF7567C88195ffcea', 
                    operation = '', 
                    scheme = '', 
                    operand_count = 56, 
                    result_ciphertext = '', 
                    noise_budget_remaining = 56, 
                    status = 'completed', )
            )
        else:
            return ComputeIncoCiphertexts200Response(
        )
        """

    def testComputeIncoCiphertexts200Response(self):
        """Test ComputeIncoCiphertexts200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
