# coding: utf-8

"""
    Sipher — Privacy-as-a-Skill API

    REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

    The version of the OpenAPI document: 0.1.0
    Contact: hello@sip-protocol.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sipher_client.models.compliance_report_request import ComplianceReportRequest

class TestComplianceReportRequest(unittest.TestCase):
    """ComplianceReportRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ComplianceReportRequest:
        """Test ComplianceReportRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ComplianceReportRequest`
        """
        model = ComplianceReportRequest()
        if include_optional:
            return ComplianceReportRequest(
                viewing_key = sipher_client.models.viewing_key.ViewingKey(
                    key = '0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef', 
                    path = '', 
                    hash = '0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef', ),
                start_time = 56,
                end_time = 56,
                auditor_id = '',
                auditor_verification = sipher_client.models.compliance_disclose_request_auditor_verification.complianceDisclose_request_auditorVerification(
                    auditor_key_hash = '0x2', 
                    nonce = '0x2', ),
                include_counterparties = True
            )
        else:
            return ComplianceReportRequest(
                viewing_key = sipher_client.models.viewing_key.ViewingKey(
                    key = '0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef', 
                    path = '', 
                    hash = '0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef', ),
                start_time = 56,
                end_time = 56,
                auditor_id = '',
                auditor_verification = sipher_client.models.compliance_disclose_request_auditor_verification.complianceDisclose_request_auditorVerification(
                    auditor_key_hash = '0x2', 
                    nonce = '0x2', ),
        )
        """

    def testComplianceReportRequest(self):
        """Test ComplianceReportRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
