# coding: utf-8

"""
    Sipher — Privacy-as-a-Skill API

    REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

    The version of the OpenAPI document: 0.1.0
    Contact: hello@sip-protocol.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sipher_client.models.backends_compare200_response import BackendsCompare200Response

class TestBackendsCompare200Response(unittest.TestCase):
    """BackendsCompare200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BackendsCompare200Response:
        """Test BackendsCompare200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BackendsCompare200Response`
        """
        model = BackendsCompare200Response()
        if include_optional:
            return BackendsCompare200Response(
                success = True,
                data = sipher_client.models.backends_compare_200_response_data.backendsCompare_200_response_data(
                    operation = '', 
                    chain = '', 
                    comparisons = [
                        sipher_client.models.backends_compare_200_response_data_comparisons_inner.backendsCompare_200_response_data_comparisons_inner(
                            backend = '', 
                            type = '', 
                            available = True, 
                            cost_lamports = 1.337, 
                            cost_sol = '', 
                            latency_ms = 1.337, 
                            latency_category = 'fast', 
                            privacy_level = '', 
                            capabilities = [
                                ''
                                ], 
                            score = 0, 
                            recommended = True, )
                        ], 
                    recommendation = sipher_client.models.backends_compare_200_response_data_recommendation.backendsCompare_200_response_data_recommendation(
                        best_overall = '', 
                        best_value = '', 
                        fastest = '', 
                        most_private = '', 
                        reasoning = '', ), )
            )
        else:
            return BackendsCompare200Response(
        )
        """

    def testBackendsCompare200Response(self):
        """Test BackendsCompare200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
