# coding: utf-8

"""
    Sipher — Privacy-as-a-Skill API

    REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

    The version of the OpenAPI document: 0.1.0
    Contact: hello@sip-protocol.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sipher_client.models.error_response import ErrorResponse

class TestErrorResponse(unittest.TestCase):
    """ErrorResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ErrorResponse:
        """Test ErrorResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ErrorResponse`
        """
        model = ErrorResponse()
        if include_optional:
            return ErrorResponse(
                success = false,
                error = sipher_client.models.get_health_503_response_error.getHealth_503_response_error(
                    code = '', 
                    message = '', 
                    details = null, )
            )
        else:
            return ErrorResponse(
                success = false,
                error = sipher_client.models.get_health_503_response_error.getHealth_503_response_error(
                    code = '', 
                    message = '', 
                    details = null, ),
        )
        """

    def testErrorResponse(self):
        """Test ErrorResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
