# coding: utf-8

"""
    Sipher — Privacy-as-a-Skill API

    REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

    The version of the OpenAPI document: 0.1.0
    Contact: hello@sip-protocol.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sipher_client.models.private_swap_request import PrivateSwapRequest

class TestPrivateSwapRequest(unittest.TestCase):
    """PrivateSwapRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PrivateSwapRequest:
        """Test PrivateSwapRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PrivateSwapRequest`
        """
        model = PrivateSwapRequest()
        if include_optional:
            return PrivateSwapRequest(
                sender = 'S1PMFspo4W6BYKHWkHNF7kZ3fnqibEXg3LQjxepS9at',
                input_mint = 'S1PMFspo4W6BYKHWkHNF7kZ3fnqibEXg3LQjxepS9at',
                input_amount = '1000000000',
                output_mint = 'S1PMFspo4W6BYKHWkHNF7kZ3fnqibEXg3LQjxepS9at',
                slippage_bps = 1,
                recipient_meta_address = sipher_client.models.private_swap_request_recipient_meta_address.privateSwap_request_recipientMetaAddress(
                    spending_key = '0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef', 
                    viewing_key = '0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef', 
                    chain = 'solana', 
                    label = '', )
            )
        else:
            return PrivateSwapRequest(
                sender = 'S1PMFspo4W6BYKHWkHNF7kZ3fnqibEXg3LQjxepS9at',
                input_mint = 'S1PMFspo4W6BYKHWkHNF7kZ3fnqibEXg3LQjxepS9at',
                input_amount = '1000000000',
                output_mint = 'S1PMFspo4W6BYKHWkHNF7kZ3fnqibEXg3LQjxepS9at',
        )
        """

    def testPrivateSwapRequest(self):
        """Test PrivateSwapRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
