# coding: utf-8

"""
    Sipher — Privacy-as-a-Skill API

    REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

    The version of the OpenAPI document: 0.1.0
    Contact: hello@sip-protocol.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sipher_client.models.commitment_verify_request import CommitmentVerifyRequest

class TestCommitmentVerifyRequest(unittest.TestCase):
    """CommitmentVerifyRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CommitmentVerifyRequest:
        """Test CommitmentVerifyRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CommitmentVerifyRequest`
        """
        model = CommitmentVerifyRequest()
        if include_optional:
            return CommitmentVerifyRequest(
                commitment = '0x2',
                value = '4',
                blinding_factor = '0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef'
            )
        else:
            return CommitmentVerifyRequest(
                commitment = '0x2',
                value = '4',
                blinding_factor = '0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef',
        )
        """

    def testCommitmentVerifyRequest(self):
        """Test CommitmentVerifyRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
