# coding: utf-8

"""
    Sipher — Privacy-as-a-Skill API

    REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

    The version of the OpenAPI document: 0.1.0
    Contact: hello@sip-protocol.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sipher_client.models.proofs_funding_generate200_response import ProofsFundingGenerate200Response

class TestProofsFundingGenerate200Response(unittest.TestCase):
    """ProofsFundingGenerate200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProofsFundingGenerate200Response:
        """Test ProofsFundingGenerate200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProofsFundingGenerate200Response`
        """
        model = ProofsFundingGenerate200Response()
        if include_optional:
            return ProofsFundingGenerate200Response(
                success = True,
                data = sipher_client.models.proofs_funding_generate_200_response_data.proofsFundingGenerate_200_response_data(
                    proof = sipher_client.models.proofs_funding_generate_200_response_data_proof.proofsFundingGenerate_200_response_data_proof(
                        type = 'funding', 
                        public_inputs = [
                            ''
                            ], ), 
                    public_inputs = [
                        ''
                        ], )
            )
        else:
            return ProofsFundingGenerate200Response(
        )
        """

    def testProofsFundingGenerate200Response(self):
        """Test ProofsFundingGenerate200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
