# coding: utf-8

"""
    Sipher — Privacy-as-a-Skill API

    REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

    The version of the OpenAPI document: 0.1.0
    Contact: hello@sip-protocol.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sipher_client.models.submit_arcium_computation200_response_data import SubmitArciumComputation200ResponseData

class TestSubmitArciumComputation200ResponseData(unittest.TestCase):
    """SubmitArciumComputation200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubmitArciumComputation200ResponseData:
        """Test SubmitArciumComputation200ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubmitArciumComputation200ResponseData`
        """
        model = SubmitArciumComputation200ResponseData()
        if include_optional:
            return SubmitArciumComputation200ResponseData(
                computation_id = 'arc_62ECB020842930cc01FFCCfeEe150AC32DcAEc8a83DDD7dBF7567C88195ffcea',
                status = 'submitted',
                estimated_completion = 56,
                circuit_id = '',
                chain = '',
                input_count = 56
            )
        else:
            return SubmitArciumComputation200ResponseData(
        )
        """

    def testSubmitArciumComputation200ResponseData(self):
        """Test SubmitArciumComputation200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
