# coding: utf-8

"""
    Sipher — Privacy-as-a-Skill API

    REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

    The version of the OpenAPI document: 0.1.0
    Contact: hello@sip-protocol.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sipher_client.models.viewing_key_disclose200_response_data import ViewingKeyDisclose200ResponseData

class TestViewingKeyDisclose200ResponseData(unittest.TestCase):
    """ViewingKeyDisclose200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ViewingKeyDisclose200ResponseData:
        """Test ViewingKeyDisclose200ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ViewingKeyDisclose200ResponseData`
        """
        model = ViewingKeyDisclose200ResponseData()
        if include_optional:
            return ViewingKeyDisclose200ResponseData(
                ciphertext = '',
                nonce = '',
                viewing_key_hash = ''
            )
        else:
            return ViewingKeyDisclose200ResponseData(
        )
        """

    def testViewingKeyDisclose200ResponseData(self):
        """Test ViewingKeyDisclose200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
