# coding: utf-8

"""
    Sipher — Privacy-as-a-Skill API

    REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

    The version of the OpenAPI document: 0.1.0
    Contact: hello@sip-protocol.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sipher_client.models.compute_inco_ciphertexts200_response_data import ComputeIncoCiphertexts200ResponseData

class TestComputeIncoCiphertexts200ResponseData(unittest.TestCase):
    """ComputeIncoCiphertexts200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ComputeIncoCiphertexts200ResponseData:
        """Test ComputeIncoCiphertexts200ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ComputeIncoCiphertexts200ResponseData`
        """
        model = ComputeIncoCiphertexts200ResponseData()
        if include_optional:
            return ComputeIncoCiphertexts200ResponseData(
                computation_id = 'inc_62ECB020842930cc01FFCCfeEe150AC32DcAEc8a83DDD7dBF7567C88195ffcea',
                operation = '',
                scheme = '',
                operand_count = 56,
                result_ciphertext = '',
                noise_budget_remaining = 56,
                status = 'completed'
            )
        else:
            return ComputeIncoCiphertexts200ResponseData(
        )
        """

    def testComputeIncoCiphertexts200ResponseData(self):
        """Test ComputeIncoCiphertexts200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
