# coding: utf-8

"""
    Sipher — Privacy-as-a-Skill API

    REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

    The version of the OpenAPI document: 0.1.0
    Contact: hello@sip-protocol.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sipher_client.models.get_ready200_response_data_checks import GetReady200ResponseDataChecks

class TestGetReady200ResponseDataChecks(unittest.TestCase):
    """GetReady200ResponseDataChecks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetReady200ResponseDataChecks:
        """Test GetReady200ResponseDataChecks
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetReady200ResponseDataChecks`
        """
        model = GetReady200ResponseDataChecks()
        if include_optional:
            return GetReady200ResponseDataChecks(
                solana = True,
                shutdown = True
            )
        else:
            return GetReady200ResponseDataChecks(
        )
        """

    def testGetReady200ResponseDataChecks(self):
        """Test GetReady200ResponseDataChecks"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
