# coding: utf-8

"""
    Sipher — Privacy-as-a-Skill API

    REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

    The version of the OpenAPI document: 0.1.0
    Contact: hello@sip-protocol.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sipher_client.models.proofs_fulfillment_generate200_response_data import ProofsFulfillmentGenerate200ResponseData

class TestProofsFulfillmentGenerate200ResponseData(unittest.TestCase):
    """ProofsFulfillmentGenerate200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProofsFulfillmentGenerate200ResponseData:
        """Test ProofsFulfillmentGenerate200ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProofsFulfillmentGenerate200ResponseData`
        """
        model = ProofsFulfillmentGenerate200ResponseData()
        if include_optional:
            return ProofsFulfillmentGenerate200ResponseData(
                proof = sipher_client.models.proofs_fulfillment_generate_200_response_data_proof.proofsFulfillmentGenerate_200_response_data_proof(
                    type = 'fulfillment', 
                    proof = '', 
                    public_inputs = [
                        ''
                        ], ),
                public_inputs = [
                    ''
                    ]
            )
        else:
            return ProofsFulfillmentGenerate200ResponseData(
        )
        """

    def testProofsFulfillmentGenerate200ResponseData(self):
        """Test ProofsFulfillmentGenerate200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
