# coding: utf-8

"""
    Sipher — Privacy-as-a-Skill API

    REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

    The version of the OpenAPI document: 0.1.0
    Contact: hello@sip-protocol.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sipher_client.api.arcium_api import ArciumApi


class TestArciumApi(unittest.TestCase):
    """ArciumApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ArciumApi()

    def tearDown(self) -> None:
        pass

    def test_decrypt_arcium_result(self) -> None:
        """Test case for decrypt_arcium_result

        Decrypt computation result
        """
        pass

    def test_get_arcium_computation_status(self) -> None:
        """Test case for get_arcium_computation_status

        Get computation status
        """
        pass

    def test_submit_arcium_computation(self) -> None:
        """Test case for submit_arcium_computation

        Submit MPC computation
        """
        pass


if __name__ == '__main__':
    unittest.main()
