# coding: utf-8

"""
    Sipher — Privacy-as-a-Skill API

    REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

    The version of the OpenAPI document: 0.1.0
    Contact: hello@sip-protocol.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sipher_client.models.compliance_report200_response_data_summary import ComplianceReport200ResponseDataSummary

class TestComplianceReport200ResponseDataSummary(unittest.TestCase):
    """ComplianceReport200ResponseDataSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ComplianceReport200ResponseDataSummary:
        """Test ComplianceReport200ResponseDataSummary
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ComplianceReport200ResponseDataSummary`
        """
        model = ComplianceReport200ResponseDataSummary()
        if include_optional:
            return ComplianceReport200ResponseDataSummary(
                total_transactions = 56,
                total_volume = '',
                unique_counterparties = 56,
                encrypted_transactions = [
                    ''
                    ]
            )
        else:
            return ComplianceReport200ResponseDataSummary(
        )
        """

    def testComplianceReport200ResponseDataSummary(self):
        """Test ComplianceReport200ResponseDataSummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
