# coding: utf-8

"""
    Sipher — Privacy-as-a-Skill API

    REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

    The version of the OpenAPI document: 0.1.0
    Contact: hello@sip-protocol.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sipher_client.models.privacy_score200_response_data import PrivacyScore200ResponseData

class TestPrivacyScore200ResponseData(unittest.TestCase):
    """PrivacyScore200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PrivacyScore200ResponseData:
        """Test PrivacyScore200ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PrivacyScore200ResponseData`
        """
        model = PrivacyScore200ResponseData()
        if include_optional:
            return PrivacyScore200ResponseData(
                address = '',
                score = 0,
                grade = 'A',
                transactions_analyzed = 56,
                factors = sipher_client.models.privacy_score_200_response_data_factors.privacyScore_200_response_data_factors(
                    address_reuse = sipher_client.models.privacy_score_200_response_data_factors_address_reuse.privacyScore_200_response_data_factors_addressReuse(
                        score = 56, 
                        detail = '', ), 
                    amount_patterns = sipher_client.models.privacy_score_200_response_data_factors_address_reuse.privacyScore_200_response_data_factors_addressReuse(
                        score = 56, 
                        detail = '', ), 
                    timing_correlation = , 
                    counterparty_exposure = , ),
                recommendations = [
                    ''
                    ]
            )
        else:
            return PrivacyScore200ResponseData(
        )
        """

    def testPrivacyScore200ResponseData(self):
        """Test PrivacyScore200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
