# coding: utf-8

"""
    Sipher — Privacy-as-a-Skill API

    REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

    The version of the OpenAPI document: 0.1.0
    Contact: hello@sip-protocol.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sipher_client.models.stealth_generate_batch200_response import StealthGenerateBatch200Response

class TestStealthGenerateBatch200Response(unittest.TestCase):
    """StealthGenerateBatch200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StealthGenerateBatch200Response:
        """Test StealthGenerateBatch200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StealthGenerateBatch200Response`
        """
        model = StealthGenerateBatch200Response()
        if include_optional:
            return StealthGenerateBatch200Response(
                success = True,
                data = sipher_client.models.stealth_generate_batch_200_response_data.stealthGenerateBatch_200_response_data(
                    results = [
                        sipher_client.models.stealth_generate_batch_200_response_data_results_inner.stealthGenerateBatch_200_response_data_results_inner(
                            index = 56, 
                            success = True, 
                            data = sipher_client.models.stealth_generate_200_response_data.stealthGenerate_200_response_data(
                                meta_address = sipher_client.models.stealth_meta_address.StealthMetaAddress(
                                    spending_key = '0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef', 
                                    viewing_key = '0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef', 
                                    chain = 'solana', 
                                    label = '', ), 
                                spending_private_key = '0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef', 
                                viewing_private_key = '0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef', ), 
                            error = '', )
                        ], 
                    summary = sipher_client.models.stealth_generate_batch_200_response_data_summary.stealthGenerateBatch_200_response_data_summary(
                        total = 56, 
                        succeeded = 56, 
                        failed = 56, ), )
            )
        else:
            return StealthGenerateBatch200Response(
        )
        """

    def testStealthGenerateBatch200Response(self):
        """Test StealthGenerateBatch200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
