# coding: utf-8

"""
    Sipher — Privacy-as-a-Skill API

    REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

    The version of the OpenAPI document: 0.1.0
    Contact: hello@sip-protocol.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sipher_client.models.scan_payments200_response_data_payments_inner import ScanPayments200ResponseDataPaymentsInner

class TestScanPayments200ResponseDataPaymentsInner(unittest.TestCase):
    """ScanPayments200ResponseDataPaymentsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScanPayments200ResponseDataPaymentsInner:
        """Test ScanPayments200ResponseDataPaymentsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScanPayments200ResponseDataPaymentsInner`
        """
        model = ScanPayments200ResponseDataPaymentsInner()
        if include_optional:
            return ScanPayments200ResponseDataPaymentsInner(
                stealth_address = '',
                ephemeral_public_key = '',
                tx_signature = '',
                slot = 56,
                timestamp = 56
            )
        else:
            return ScanPayments200ResponseDataPaymentsInner(
        )
        """

    def testScanPayments200ResponseDataPaymentsInner(self):
        """Test ScanPayments200ResponseDataPaymentsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
