# coding: utf-8

"""
    Sipher — Privacy-as-a-Skill API

    REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

    The version of the OpenAPI document: 0.1.0
    Contact: hello@sip-protocol.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sipher_client.api.privacy_api import PrivacyApi


class TestPrivacyApi(unittest.TestCase):
    """PrivacyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PrivacyApi()

    def tearDown(self) -> None:
        pass

    def test_privacy_score(self) -> None:
        """Test case for privacy_score

        Analyze wallet privacy score
        """
        pass


if __name__ == '__main__':
    unittest.main()
