# coding: utf-8

"""
    Sipher — Privacy-as-a-Skill API

    REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

    The version of the OpenAPI document: 0.1.0
    Contact: hello@sip-protocol.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sipher_client.models.cspl_wrap_request import CsplWrapRequest

class TestCsplWrapRequest(unittest.TestCase):
    """CsplWrapRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CsplWrapRequest:
        """Test CsplWrapRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CsplWrapRequest`
        """
        model = CsplWrapRequest()
        if include_optional:
            return CsplWrapRequest(
                mint = 'S1PMFspo4W6BYKHWkHNF7kZ3fnqibEXg3LQjxepS9at',
                amount = '1000000000',
                owner = 'S1PMFspo4W6BYKHWkHNF7kZ3fnqibEXg3LQjxepS9at',
                create_account = True
            )
        else:
            return CsplWrapRequest(
                mint = 'S1PMFspo4W6BYKHWkHNF7kZ3fnqibEXg3LQjxepS9at',
                amount = '1000000000',
                owner = 'S1PMFspo4W6BYKHWkHNF7kZ3fnqibEXg3LQjxepS9at',
        )
        """

    def testCsplWrapRequest(self):
        """Test CsplWrapRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
