# coding: utf-8

"""
    Sipher — Privacy-as-a-Skill API

    REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

    The version of the OpenAPI document: 0.1.0
    Contact: hello@sip-protocol.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class CsplTransferRequest(BaseModel):
    """
    CsplTransferRequest
    """ # noqa: E501
    cspl_mint: StrictStr = Field(description="C-SPL token mint identifier", alias="csplMint")
    var_from: Annotated[str, Field(min_length=32, strict=True, max_length=44)] = Field(description="Base58-encoded Solana public key", alias="from")
    to: Annotated[str, Field(min_length=32, strict=True, max_length=44)] = Field(description="Base58-encoded Solana public key")
    encrypted_amount: Annotated[str, Field(strict=True)] = Field(description="Encrypted transfer amount as hex", alias="encryptedAmount")
    memo: Optional[Annotated[str, Field(strict=True, max_length=256)]] = Field(default=None, description="Optional memo")
    __properties: ClassVar[List[str]] = ["csplMint", "from", "to", "encryptedAmount", "memo"]

    @field_validator('encrypted_amount')
    def encrypted_amount_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^0x[0-9a-fA-F]+$", value):
            raise ValueError(r"must validate the regular expression /^0x[0-9a-fA-F]+$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CsplTransferRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CsplTransferRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "csplMint": obj.get("csplMint"),
            "from": obj.get("from"),
            "to": obj.get("to"),
            "encryptedAmount": obj.get("encryptedAmount"),
            "memo": obj.get("memo")
        })
        return _obj


