# coding: utf-8

"""
    Sipher — Privacy-as-a-Skill API

    REST API wrapping SIP Protocol's privacy SDK for Solana agents. Stealth addresses, Pedersen commitments, shielded transfers, and viewing key compliance.

    The version of the OpenAPI document: 0.1.0
    Contact: hello@sip-protocol.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from sipher_client.models.transfer_private200_response_data_chain_data import TransferPrivate200ResponseDataChainData
from typing import Optional, Set
from typing_extensions import Self

class TransferPrivate200ResponseData(BaseModel):
    """
    TransferPrivate200ResponseData
    """ # noqa: E501
    chain: Optional[StrictStr] = None
    curve: Optional[StrictStr] = None
    stealth_address: Optional[StrictStr] = Field(default=None, description="Chain-native stealth address", alias="stealthAddress")
    ephemeral_public_key: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="0x-prefixed 32-byte hex string", alias="ephemeralPublicKey")
    view_tag: Optional[Annotated[int, Field(le=255, strict=True, ge=0)]] = Field(default=None, alias="viewTag")
    commitment: Optional[StrictStr] = None
    blinding_factor: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="0x-prefixed 32-byte hex string", alias="blindingFactor")
    viewing_key_hash: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="0x-prefixed 32-byte hex string", alias="viewingKeyHash")
    shared_secret: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="0x-prefixed 32-byte hex string", alias="sharedSecret")
    chain_data: Optional[TransferPrivate200ResponseDataChainData] = Field(default=None, alias="chainData")
    __properties: ClassVar[List[str]] = ["chain", "curve", "stealthAddress", "ephemeralPublicKey", "viewTag", "commitment", "blindingFactor", "viewingKeyHash", "sharedSecret", "chainData"]

    @field_validator('curve')
    def curve_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['ed25519', 'secp256k1']):
            raise ValueError("must be one of enum values ('ed25519', 'secp256k1')")
        return value

    @field_validator('ephemeral_public_key')
    def ephemeral_public_key_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^0x[0-9a-fA-F]{64}$", value):
            raise ValueError(r"must validate the regular expression /^0x[0-9a-fA-F]{64}$/")
        return value

    @field_validator('blinding_factor')
    def blinding_factor_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^0x[0-9a-fA-F]{64}$", value):
            raise ValueError(r"must validate the regular expression /^0x[0-9a-fA-F]{64}$/")
        return value

    @field_validator('viewing_key_hash')
    def viewing_key_hash_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^0x[0-9a-fA-F]{64}$", value):
            raise ValueError(r"must validate the regular expression /^0x[0-9a-fA-F]{64}$/")
        return value

    @field_validator('shared_secret')
    def shared_secret_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^0x[0-9a-fA-F]{64}$", value):
            raise ValueError(r"must validate the regular expression /^0x[0-9a-fA-F]{64}$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TransferPrivate200ResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of chain_data
        if self.chain_data:
            _dict['chainData'] = self.chain_data.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TransferPrivate200ResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "chain": obj.get("chain"),
            "curve": obj.get("curve"),
            "stealthAddress": obj.get("stealthAddress"),
            "ephemeralPublicKey": obj.get("ephemeralPublicKey"),
            "viewTag": obj.get("viewTag"),
            "commitment": obj.get("commitment"),
            "blindingFactor": obj.get("blindingFactor"),
            "viewingKeyHash": obj.get("viewingKeyHash"),
            "sharedSecret": obj.get("sharedSecret"),
            "chainData": TransferPrivate200ResponseDataChainData.from_dict(obj["chainData"]) if obj.get("chainData") is not None else None
        })
        return _obj


